name: payrix-api-tester E2E (post-deploy)

on:
  repository_dispatch:
    types:
      - deploy-success

jobs:
  e2e:
    uses: 1aboveio/.github/.github/workflows/e2e-post-deploy.yml@main
    with:
      commit: ${{ github.event.client_payload.commit || 'main' }}
      env: ${{ github.event.client_payload.env || 'unknown' }}
      service_url: ${{ github.event.client_payload.service_url }}
    secrets: inherit
